# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        java: [21]
        minecraft_version: [1.21, 1.21.2, 1.21.4]
    runs-on: ubuntu-22.04
    steps:
      - name: Get branch name
        id: get_branch_name
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          
      - name: Make the commit message compatible with JSON
        run: |
          # Escape the commit message for JSON
          COMMIT_MESSAGE=$(echo -n "${{ github.event.head_commit.message }}" | sed 's/%0A/\\n/g' | jq -s -Rr @json)
          COMMIT_MESSAGE=${COMMIT_MESSAGE:1:-1}
          echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_ENV
          
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v2
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'microsoft'
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew chiseledBuild
        
      - name: capture build artifacts
        if: ${{ matrix.java == '21' }} # Only upload artifacts built from latest java
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts-${{ matrix.minecraft_version }}
          path: versions/${{ matrix.minecraft_version }}/build/libs/
